name: Delete Merged Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Delete branch after merge
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          REPO=${{ github.repository }}
          echo "Deleting branch: $BRANCH_NAME"
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH_NAME
